### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by rodolfoag** [sinfo/ampersand-infinite-scroll#5]
Could you provide an example of how to use? thx.

**Comment by JGAntunes** [comment]
Hi @rodolfoag yeah sure. Some this modules are still missing a lot of info. We'll look into this asap.

**Comment by JGAntunes** [comment]
Hi @rodolfoag sorry for the late reply, but we've been doing some clean up on our repos. We've updated this as well as [ampersand-pagination-mixin](https://github.com/JGAntunes/ampersand-pagination-mixin) with some info that might be interesting to you. If you would like to see something more concrete in action you could also take a look at [this](https://github.com/sinfo/eventdeck/blob/master/client/js/views/notifications.js#L4) and [this](https://github.com/sinfo/eventdeck/blob/master/client/js/models/publicNotifications.js#L3), it's a project we have at @SINFO which is currently using the infinite scroll view to render a notification view system.

**Comment by rodolfoag** [comment]
Alright mate, thx!
